from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Any, Callable

from shared.tools.github_api import create_github_pr, fetch_dag_source
from shared.tools.slack import post_to_slack

SYSTEM_PROMPT = (Path(__file__).parent / "prompts" / "system_prompt.md").read_text()
log = logging.getLogger(__name__)


def _deterministic_troubleshoot(dag_id: str, run_id: str) -> dict[str, Any]:
    use_mocks = (
        os.environ.get("AIRFLOW_AGENT_USE_MOCKS") or os.environ.get("AGENT_USE_MOCKS", "false")
    ).lower() in {"1", "true", "yes"}
    if not use_mocks:
        raise RuntimeError(
            "Deterministic troubleshooting is only valid with AGENT_USE_MOCKS=true. "
            "Set AGENT_USE_MODEL=true to analyze real Airflow/GitHub data."
        )

    task_id = "transform"
    logs = "KeyError: 'rowz'"
    filename = f"{dag_id}.py"
    source = fetch_dag_source(str(filename).split("/")[-1])

    likely_cause = "The transform task reads data['rowz'], but extract returns the key 'rows'."
    suggested_fix = "Change data['rowz'] to data['rows'] in transform, or update extract to emit 'rowz'."
    what_happened = f"{dag_id}.{task_id} failed with KeyError: 'rowz'."
    fixed_content = source.replace('data["rowz"]', 'data["rows"]')
    pr_result = create_github_pr(
        filename=filename,
        fixed_content=fixed_content,
        pr_title=f"fix({dag_id}): correct key 'rowz' to 'rows' in transform",
        pr_body=(
            f"## Agent-suggested fix\n\n"
            f"**DAG:** `{dag_id}`  \n"
            f"**Failed task:** `{task_id}`  \n\n"
            f"**Root cause:** {likely_cause}\n\n"
            f"**Change:** replaced `data[\"rowz\"]` with `data[\"rows\"]` in `transform`.\n\n"
            f"> :robot: Auto-generated by the Airflow troubleshooting agent. Review before merging."
        ),
    )
    pr_url = pr_result.get("pr_url")
    slack_result = post_to_slack(
        dag_id=dag_id,
        task_id=task_id,
        run_id=run_id,
        what_happened=what_happened,
        likely_cause=likely_cause,
        suggested_fix=suggested_fix,
        pr_url=pr_url,
    )

    return {
        "dag_id": dag_id,
        "run_id": run_id,
        "task_id": task_id,
        "summary": what_happened,
        "likely_cause": likely_cause,
        "suggested_fix": suggested_fix,
        "pr_url": pr_url,
        "log_excerpt": logs[-1000:],
        "source_excerpt": source[:1000],
        "slack": slack_result,
    }


def _payload_prompt(payload: dict[str, Any]) -> str:
    return (
        "Troubleshoot this Airflow failure using the JSON payload below. "
        "The payload already contains the failed task and log excerpt from Airflow. "
        "Read the DAG source from GitHub, analyze the logs and source together, "
        "open a draft GitHub PR with the corrected DAG, then post a clear "
        "explanation with the PR link to Slack.\n\n"
        f"{json.dumps(payload, indent=2, sort_keys=True)}"
    )


def troubleshoot(payload: dict[str, Any], model_runner: Callable[[str], Any] | None = None) -> dict[str, Any]:
    dag_id = payload["dag_id"]
    run_id = payload["run_id"]
    log.info("Troubleshooting %s / %s", dag_id, run_id)

    if model_runner is None:
        return _deterministic_troubleshoot(dag_id, run_id)

    prompt = _payload_prompt(payload)
    result = model_runner(prompt)
    return {"summary": str(result)}
